# Use root/example as user/password credentials
services:
    # (this is just an example, not intended to be a production configuration)
  db:
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mercly-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
  notifications:
    restart: unless-stopped
    container_name: NotificationsService
    build:
      context: ./NotificationsService
      dockerfile: deploy/Dockerfile
    # allocate as many volumes as necessary, if needed.
    volumes:
      - ./NotificationsService/storage/app:/var/www/html/storage/app
    environment:
      APP_NAME: ${APP_NAME_NOTIFICATIONS}
      APP_ENV: ${APP_ENV_NOTIFICATIONS}
      APP_DEBUG: ${APP_DEBUG_NOTIFICATIONS}
      APP_KEY: ${APP_KEY_NOTIFICATIONS}
      APP_URL: ${APP_URL_NOTIFICATIONS}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_MAILER: ${MAIL_MAILER_NOTIFICATIONS}
      MAIL_HOST: ${MAIL_HOST_NOTIFICATIONS}
      MAIL_PORT: ${MAIL_PORT_NOTIFICATIONS}
      MAIL_USERNAME: ${MAIL_USERNAME_NOTIFICATIONS}
      MAIL_PASSWORD: ${MAIL_PASSWORD_NOTIFICATIONS}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION_NOTIFICATIONS}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS_NOTIFICATIONS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME_NOTIFICATIONS}
    ports:
      - "8080:80"
    networks:
      - mercly-network
    depends_on:
      - db
  payment:
    restart: unless-stopped
    container_name: PaymentService
    build:
      context: ./PaymentService
      dockerfile: deploy/Dockerfile
    # allocate as many volumes as necessary, if needed.
    volumes:
      - ./PaymentService/storage/app:/var/www/html/storage/app
    environment:
      APP_NAME: ${APP_NAME_PAYMENT}
      APP_ENV: ${APP_ENV_PAYMENT}
      APP_DEBUG: ${APP_DEBUG_PAYMENT}
      APP_KEY: ${APP_KEY_PAYMENT}
      APP_URL: ${APP_URL_PAYMENT}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_MAILER: ${MAIL_MAILER_PAYMENT}
      MAIL_HOST: ${MAIL_HOST_PAYMENT}
      MAIL_PORT: ${MAIL_PORT_PAYMENT}
      MAIL_USERNAME: ${MAIL_USERNAME_PAYMENT}
      MAIL_PASSWORD: ${MAIL_PASSWORD_PAYMENT}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION_PAYMENT}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS_PAYMENT}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME_PAYMENT}
    ports:
      - "8081:80"
    networks:
      - mercly-network
    depends_on:
      - db
  product-service:
    build: ./product-service
    ports:
      - "8082:8081"
    depends_on:
      - cart-service
  cart-service:
    build: ./cart-service
    ports:
      - "8083:8082"

volumes:
  db-data:

networks:
  mercly-network:
    driver: bridge