version: '3.8'

services:
  db2:
    image: mysql:8
    env_file: ./.env
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - mercly-network
  app:
    build: .
    depends_on:
      - db2
    links:
      - db2
    ports:
      - "3000:3000"
    networks:
      - mercly-network

networks:
  mercly-network:
    external: true    