
#docker compose para las apis 
services:
  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      - cart-service

  cart-service:
    build: ./cart-service
    ports:
      - "8082:8082"
