version: '3'
services:
  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    networks:
      - mynetwork

  cart-service:
    build: ./cart-service
    ports:
      - "8082:8082"
    networks:
      - mynetwork
    depends_on:
      - product-service

networks:
  mynetwork:
    driver: bridge